# Coding Temple's Data Analytics Program  
---
# Advanced Python - Intro to `numpy`
---



## Part 1: Working with `numpy`


### 1.1 Importing `numpy`

We've already used the `numpy` package by importing it and assigning it the standard alias of `np`. Do this again in the following cell - the more you practice typing these lines of code, the easier it will be to remember.

In [1]:
# Import numpy and assign it the standard alias
# YOUR CODE HERE
import numpy as np

### 1.1 Solution - Run this cell to check your answer in 1.1. Please do not edit the values in this cell!

In [2]:
# DO NOT EDIT THIS CELL
assert np.__name__ == 'numpy', 'Make sure that you have properly imported numpy and aliased it as np!'

### 1.2 Generate random numbers

Create a `(5,3)` `numpy` array of random integer values between 0 and 100.

Use the the `random()` method in numpy to generate these integers. Name your new variable `myarray`. You should also print the array to check it's dimensions and values.

In [3]:
np.random.randint(100)

93

In [4]:
# Generate your random numbers
np.random.seed(1) #Seed generated for reproducibility
myarray = np.random.randint(100, size = (5,3))

#YOUR CODE HEREm

# Print out the array
myarray

array([[37, 12, 72],
       [ 9, 75,  5],
       [79, 64, 16],
       [ 1, 76, 71],
       [ 6, 25, 50]])

### 1.2 Solution - Run the following cell to check your answer.

In [5]:
#DO NOT EDIT THIS CELL

#Verify the array was created with the correct name and has the proper shape
assert myarray.shape == (5,3), 'Make sure you create an array with the proper shape!'

### 1.3 Calculate BMI 

Using the two lists provided, please calculate the BMI(body mass index) of each individual using NDArrays. Save the variable containing your results as `bmi`

The formula for BMI in pounds and inches can be defined as: $BMI= \frac{703 * weight} {(height)^2}$

In [6]:
height = [55, 120, 90, 100]
weight = [170, 180, 190, 200]

bmi = (703*np.array(weight))/(np.array(height)**2)
bmi.astype(int)

array([39,  8, 16, 14])

### 1.3 Solution: Run the following cell to check your answer.

In [7]:
assert 'bmi' in dir() , 'Make sure you have saved your results to the proper variable name!'
assert type(bmi) == np.ndarray, 'Make sure that you made the calculation using an NDArray for both height and weight!'

### 1.4 Create a function 

Create a function named `my_func` that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [8]:
def my_func(rows,columns):
    #gerenate a rando matrix with the specified dimensions
    np.random.seed(2)
    np.random.rand(rows, columns)
    random_matrix = np.random.randint(101, size = (3,3))
    return random_matrix

my_func


<function __main__.my_func(rows, columns)>

### 1.5 Array practice

Time for some more practice. Run each of these tasks in the separate code cell listed below:

1.  Return the first row
2.  Return the last column
3.  Return the third column values from the 4th and 5th rows
4.  Multiply every value in the array by 2
5.  Divide every value by 3
6.  Increase the values in the first row by 12
7. Calculate the mean of the first column
8. Calculate the median of the array _after_ removing the 2 smallest values in the array
9. Calculate the standard deviation of the first 3 rows
10. Return values greater than 25 in the second column
11. Return values less than 40 in the array

In [9]:
# 1. Return the first row:
myarray[0,:]

array([37, 12, 72])

In [10]:
# 2. Return the last column
myarray[:,-1]

array([72,  5, 16, 71, 50])

In [11]:
# 3. Return the third column values from the 4th and 5th rows
myarray[3:5,2]



array([71, 50])

In [12]:
# 4. Multiply every value in the array by 2
myarray *2

array([[ 74,  24, 144],
       [ 18, 150,  10],
       [158, 128,  32],
       [  2, 152, 142],
       [ 12,  50, 100]])

In [13]:
# 5. Divide every value by 3
myarray / 3

array([[12.33333333,  4.        , 24.        ],
       [ 3.        , 25.        ,  1.66666667],
       [26.33333333, 21.33333333,  5.33333333],
       [ 0.33333333, 25.33333333, 23.66666667],
       [ 2.        ,  8.33333333, 16.66666667]])

In [14]:
# 6. Increase the values in the first row by 12
myarray[0]+12


array([49, 24, 84])

In [17]:
# 7. Calculate the mean of the first column
int(np.mean(myarray[:,0]))


26

In [18]:
# 8. Calculate the median of the array after removing the 2 smallest values in the array
new_array = np.sort(myarray, axis = None)

new_array = np.delete(new_array, new_array.argmin())
print(new_array)

[ 5  6  9 12 16 25 37 50 64 71 72 75 76 79]


In [19]:
# 9. Calculate the standard deviation of the first 3 rows
# Generate a new array to work on
np.random.randint(101)
np.random.seed(2) # New seed for new array
array2 = np.random.randint(101, size = (5,3))

print(np.std(array2[0:3]))

25.81128091014125


In [20]:
# 10. Return values in the second column greater than 25
condition = array2[:,1] > 25
condition




array([False,  True, False,  True,  True])

In [25]:
# 11. Return values < 40 in the array
condition_list = myarray[:] <40
condition_list

array([[ True,  True, False],
       [ True, False,  True],
       [False, False,  True],
       [ True, False, False],
       [ True,  True, False]])

### Solution 1.5: Run the following cell to view the solution for each of the above tasks.

A new array will be generated to demonstrate the solution - the values will not be the same as your array. But the code for each task will still apply.

In [32]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.3

# SOLUTION: Make sure you have completed all of the above tasks
# Generate your random numbers (NEW ARRAY)
myarray = np.random.randint(100, size=(5, 3))
print('The generated array: \n', myarray)
print('\n')

# 1. Return the first row:
print('1. The first row: ', myarray[0])
print('\n')

# 2. Return the last column
print('2. The last column: ', myarray[:,-1])
print('\n')

# 3. Return the third column values from the 4th and 5th rows
print('3. The 3rd column, 4th & 5th rows: ', myarray[3:5,2])
print('\n')

# 4. Multiply every value in the array by 2
# (operates on the original array)
print('4. Multiply by 2: \n', myarray * 2)
print('\n')

# 5. Divide every value by 3
# (operates on the original array)
print('5. Divide by 3: \n', myarray / 3)
print('\n')

# 6. Increase the values in the first row by 12
# (operates on the original array)
print('6. Add 12 to the first row: \n', myarray[0,:] + 12)
print('\n')

# 7. Calculate the mean of the first column
print('7. The mean of the 1st column: ', myarray[:,0].mean())
print('\n')

# 8. Calculate the median of the array after removing the 2 smallest values in the array
# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)
# remove two smallest values
myarray = myarray[2:]
# calculate the median
print('8. The median after removing the 2 smallest values: ', np.median(myarray))
print('\n')

# 9. Calculate the standard deviation of the first 3 rows
# Generate new array first:
myarray = np.random.randint(100, size=(5, 3))
# Then calculate the std:
print('9. The standard deviation is: ', np.std(myarray[0:3,:]))
print('\n')

# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
condition = myarray[:,1] > 25
# Apply the mask
print('10. All values in 2nd column > 25: \n', myarray[condition])
print('\n')

# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition = myarray < 40
# apply the mask
print('11. All values < 40: \n', myarray[condition])

The generated array: 
 [[31 90 20]
 [37 39 67]
 [ 4 42 51]
 [38 33 58]
 [67 69 88]]


1. The first row:  [31 90 20]


2. The last column:  [20 67 51 58 88]


3. The 3rd column, 4th & 5th rows:  [58 88]


4. Multiply by 2: 
 [[ 62 180  40]
 [ 74  78 134]
 [  8  84 102]
 [ 76  66 116]
 [134 138 176]]


5. Divide by 3: 
 [[10.33333333 30.          6.66666667]
 [12.33333333 13.         22.33333333]
 [ 1.33333333 14.         17.        ]
 [12.66666667 11.         19.33333333]
 [22.33333333 23.         29.33333333]]


6. Add 12 to the first row: 
 [ 43 102  32]


7. The mean of the 1st column:  35.4


8. The median after removing the 2 smallest values:  51.0


9. The standard deviation is:  18.755739862180263


10. All values in 2nd column > 25: 
 [[68 46 70]
 [95 83 31]
 [66 80 52]
 [76 50  4]
 [90 63 79]]


11. All values < 40: 
 [31  4]
